### DISCUSSION TITLE
Caddyfile not forwarding IP

### DISCUSSION THREAD

**Discussion by DieSchoeneWolke** [matrix-org/dendrite#3185] [Help & Support]
Hello I run caddy2 as a reverse proxy but my IP is not getting forwarded and I cannot see any channels from outside in Element.
Anybody knows what I have done wrong? Thank you for your replies!

`Caddyfile` according to the example
```
mydomain.com {
	header /.well-known/matrix/* Content-Type application/json
	header /.well-known/matrix/* Access-Control-Allow-Origin *
	respond /.well-known/matrix/server `{"m.server": "matrix.mydomain.com:443"}`
	respond /.well-known/matrix/client `{"m.homeserver": {"base_url": "https://matrix.mydomain.com"}}`
}

# The actual domain name whereby your Matrix server is accessed.
matrix.mydomain.com {
	# Set localhost:8008 to the address of your Dendrite server, if different
	reverse_proxy /_matrix/* localhost:64614
}

elementwebui.mydomain.com {
    reverse_proxy localhost:64616
}
```

`docker-compose.yml`
```
  monolith:
    container_name: Dendrite-Monolith
    image: matrixdotorg/dendrite-monolith:latest
    ports:
      - "64614:8008"
      - "64615:8448"
```

`dendrite.yaml`
```
# Configuration for the Sync API.
sync_api:
  # This option controls which HTTP header to inspect to find the real remote IP
  # address of the client. This is likely required if Dendrite is running behind
  # a reverse proxy server.
  real_ip_header: X-Real-IP
```
