### ISSUE TITLE
Implement registering with an email support

### ISSUE THREAD

**Issue by Kegsay** [matrix-org/dendrite#1298]
Spec: https://matrix.org/docs/spec/client_server/r0.6.1#email-based-identity-homeserver
Sytests:
```
    × Can register using an email address
```

**Comment by Kegsay** [comment]
Great, thanks! Check out #dendrite-dev:matrix.org if you want some help :)

**Comment by sumitks866** [comment]
Hey @rohitgeddam ! are you working on this issue? If not, then I would like to give to work on it

**Comment by PiotrKozimor** [comment]
The `Derived` struct was about to be deleted - #889, #1230. There is `Registration` field in it which contains allowable authentication flows. To my understanding it is not used yet. How do we want to populate it?

**Comment by PiotrKozimor** [comment]
I want to take another approach on it: dendrite will send confirmation email on it's own. This would also enable another requests to be handled internally: 
 - POST /_matrix/client/r0/account/password/email/requestToken
 - POST /_matrix/client/r0/account/3pid/email/requestToken

It would also enable [logging with email](https://github.com/matrix-org/dendrite/issues/1858) as long as ID servers would no longer be used.

Regarding configuration - I want to pass allowed flows and parameters explicitly in it, e.g.:
```yaml
client_api:
  registration:
    flows:
      - stages:
        - m.login.recaptcha
        - m.login.email.identity
    parameters: 
      m.login.recaptcha:
        public_key: foobar
```
 It would be validated on dendrite startup and any error would be reported as fatal. If SMTP configuration will be passed to dendrite, user could pass `m.login.email.identity` stage to flow.

Any thoughts on this?
