### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by cyberb** [matrix-org/dendrite#1813]
I am new to matrix and I would like to add dendrite to Syncloud store.
For this I need LDAP integration (login, user creation), which I can try adding if there is no working solution is available yet.

**Comment by drequivalent** [comment]
YES PLEASE!

**Comment by cyberb** [comment]
https://github.com/matrix-org/dendrite/pull/2986

**Comment by cyberb** [comment]
So it was rejected in favour of the future OIDC (which is not available right now as I understand)
For those who are desperate like me to get LDAP support right now, feel free to use my branch which I will rebase from time to time.
https://github.com/cyberb/dendrite/commits/syncloud

**Comment by cyberb** [comment]
it has this new config section:
```
 ldap:
    enabled: true
    uri: "ldap://localhost:389"
    base_dn: "dc=syncloud,dc=org"

    # admin bind modes uses a separate admin ldap account to perform user search
    admin_bind_enabled: true
    admin_bind_dn: "cn=admin,dc=syncloud,dc=org"
    admin_bind_password: "syncloud"
    search_base_dn: "ou=users,dc=syncloud,dc=org"
    search_filter: "(&(objectclass=inetOrgPerson)(cn={username}))"
    search_attribute: "cn"

    # direct user bind if admin bind is disabled
    user_bind_dn: "cn={username},ou=users,dc=syncloud,dc=org"

    # is user an admin or not
    admin_group_dn: "cn=syncloud,ou=groups,dc=syncloud,dc=org"
    admin_group_filter: "(memberUid={username})"
    admin_group_attribute: "memberUid"
```
