### ISSUE TITLE
Appservice receiving events from rooms it shouldn't

### ISSUE THREAD

**Issue by git-bruh** [matrix-org/dendrite#1835]
I have an appservice with the following `appservice.yaml`:

```
id: "discord"
url: "http://127.0.0.1:1234"
as_token: "[REDACTED]"
hs_token: "[REDACTED]"
sender_localpart: "appservice-discord"
namespaces:
  users:
    - exclusive: true
      regex: "@_discord.*"
    - regex: "@appservice.*" # Dendrite bug, appservice doesn't receive it's own DM events
  aliases:
    - exclusive: true
      regex: "#_discord.*"
  rooms: []
```

For some reason, dendrite sends my appservice events for the room`#matrix-dev:matrix.org` that it isn't registered for. I'm on a few other public rooms belonging to matrix.org but the appservice is not sent any events from them, as one would expect. How can i debug what's going wrong with this particular room ?

I'm running a dendrite that was built some days before commit https://github.com/matrix-org/dendrite/commit/af41f6d4549759afd7f52f780b40abe2834ab4c0.
