### ISSUE TITLE
Configuration of secrets through environment variables

### ISSUE THREAD

**Issue by RobinMcCorkell** [matrix-org/dendrite#1958]
**Description:**

The configuration file currently embeds secrets (e.g. database credentials, or registration shared secret) as plain text fields. In some deployment systems such as Kubernetes, this will expose those secrets, and prevents usage of secret management like Vault.

Support for specifying secrets (or more generally, any configuration option) via environment variables would fix this.

I found https://github.com/matrix-org/dendrite/issues/393 which would have covered this usecase, however it was closed with only a fraction of the features described.

**Comment by mkroman** [comment]
A common way for containers is to use environment variables to override/set a value, like:
`DENDRITE_APP_SERVICE_API_DATABASE_CONNECTION_STRING=postgresql://dendrite:itsasecret@postgres/dendrite_appservice?sslmode=disable`
and an environment variable that points to a secret file, like:
`DENDRITE_APP_SERVICE_API_DATABASE_CONNECTION_STRING_FILE=/var/secrets/postgresql_connect_string` where the `_FILE` variant takes precedent since environment variables aren't particularly private.

This isn't difficult to do, but it can lead to some annoying code.

I also have a different proposal - and that is an option to specify multiple config files to load, where every new config file will do a deep merge on the values of the previous config.

As an example: 

```yaml
# config-1.yaml
# …
app_service_api:
  internal_api:
    listen: http://0.0.0.0:7777
    connect: http://appservice_api:7777
  database:
    connection_string: not yet defined
    max_open_conns: 10
    max_idle_conns: 2
    conn_max_lifetime: -1
# …
```

```yaml
# config-2.yaml, can be stored in a secret
app_service_api:
  database:
    connection_string: postgresql://dendrite:secret@postgres/dendrite?sslmode=disable
```

and the final config will be identical to `config-1.yaml`, except for the value of `.app_service_api.database.connection_string`.

We could even take it a bit further and use those nasty YAML anchors and update the configs to avoid repeating too many options as follows:

```yaml
# config-2.yaml
database_opts: &database_opts
  connection_string: postgresql://dendrite:secret@postgres/dendrite?sslmode=disable
  max_open_conns: 15

app_service_api:
  database:
    <<: *database_opts
```
