### ISSUE TITLE
build releases workflow action

### ISSUE THREAD

**Issue by nbari** [matrix-org/dendrite#2002]
**Description:**

For automated setups could a workflow action be used to create releases?, probably this can be a starting point  (needs to be tested/adapted):

```
name: build

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [freebsd, linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v2

    - name: set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

    - uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        build_command: ./build.sh
```
