### ISSUE TITLE
Cannot send/receive messages after update to 0.6

### ISSUE THREAD

**Issue by grisu48** [matrix-org/dendrite#2143]
### Background information

* Dendrite 0.6 Monolith
* Postgres
* Docker, setup via `docker-compose`
* Client: Element (Web and Android)

I've updated the `dendrite.yaml` to version 2, especially by including the `jetstream` section as shown here:

```yaml
  # Configuration for NATS JetStream
  jetstream:
    # A list of NATS Server addresses to connect to. If none are specified, an
    # internal NATS server will be started automatically when running Dendrite
    # in monolith mode. It is required to specify the address of at least one
    # NATS Server node if running in polylith mode.
    #addresses:
    #  - jetstream:4222

    # Keep all NATS streams in memory, rather than persisting it to the storage
    # path below. This option is present primarily for integration testing and
    # should not be used on a real world Dendrite deployment.
    in_memory: false

    # Persistent directory to store JetStream streams in. This directory 
    # should be preserved across Dendrite restarts.
    storage_path: ./

    # The prefix to use for stream names for this homeserver - really only
    # useful if running more than one Dendrite on the same NATS deployment.
    topic_prefix: Dendrite
```

And the `federation_api` section

```yaml
# Configuration for the Federation API.
federation_api:
  internal_api:
    listen: http://localhost:7772  # Only used in polylith deployments
    connect: http://localhost:7772 # Only used in polylith deployments
  external_api:
    listen: http://[::]:8072
  database:
    connection_string: postgresql://matrix:<REDACTED>@192.168.122.150/dendrite_federationapi?sslmode=disable
    max_open_conns: 10
    max_idle_conns: 2
    conn_max_lifetime: -1
```

I did the configuration update mostly by looking at [this diff](https://github.com/matrix-org/dendrite/commit/161f14517669410d3e8207dc41eea5c9695f7e17#diff-dd8f3ef0612a76237776fb6e881714815b66b0c693ecd41d90213631c0dc4366)

### Description

* Since upgrade to 0.6 I cannot send/receive any messages anymore
* Messages appear to be sent, but when reloading Element (CTRL+SHIFT+R) it says "some of the messages could not be sent"

![Screenshot 2022-02-04 at 08-52-38 Element  2  IT-Syndikat](https://user-images.githubusercontent.com/1527829/152492113-e38827a5-531a-4938-8ad1-d9d2873a03f2.png)

* On Element on Android new messages are shown to be sent (the checkbox appears) but when the room is re-opened they do not show up

### Steps to reproduce

* Each message is not sent and all of my channels are quiet

### Logs

Here is a log from me, switching to a room A, posting a message, switching to a different room B, then switching back to room A and seeing that the message is not there.

[dendrite.txt](https://github.com/matrix-org/dendrite/files/8001093/dendrite.txt)
