### ISSUE TITLE
Dendrite 0.6.2 fails to sync/federate

### ISSUE THREAD

**Issue by Undef-a** [matrix-org/dendrite#2150]
## Background information

    Dendrite version or git SHA: v0.6.2 (last known good was 0.6.0)
    Monolith or Polylith?: monolith
    SQLite3 or Postgres?: postgresql
    Running in Docker?: no
    go version: 1.16.13 and 1.18beta1
    Client used (if applicable): app.element.io, Hydrogen and Fluffychat

## Description
Dendrite fails to receive new events for any room and fails to sync existing events to some clients as of version 0.6.2. In the clients, is shown by either frozen rooms and disconnection messages (element) or never finishing the initial sync (Fluffychat and Hydrogen). Rolling back to 0.6.0 resolves the issue.

The following logs may be relevant:
```
level=debug msg="Transaction: Failed to query room version for room!" error="context canceled" req.id= req.method=PUT req.path=/_matrix/federation/v1/send/<event 1>
level=debug msg="Transaction: Failed to parse event JSON of event {\"auth_events\":[\"\",\"\",\"\"],\"content\":{\"algorithm\":\"m.megolm.v1.aes-sha2\",\"ciphertext\":\"\",\"device_id\":\"\",\"sender_key\":\"\",\"session_id\":\"\"},\"depth\":20,\"hashes\":{\"sha256\":\"h0hdF/eV9J+\"},\"origin\":\"matrix.org\",\"origin_server_ts\":,\"prev_events\":[\"$\"],\"prev_state\":[],\"room_id\":\"!:.\",\"sender\":\"@\",\"signatures\":{\"matrix.org\":{\"ed25519:a_RXGa\":\"h2jmBBg\"}},\"type\":\"m.room.encrypted\",\"unsigned\":{\"age_ts\":}}" error="gomatrixserverlib: unsupported room version ''" req.id=KzqABiJjMlbU req.method=PUT req.path=/_matrix/federation/v1/send/<event 1>
http: superfluous response.WriteHeader call from github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader (delegator.go:65)
```

NOTE: user data from the logs has been stripped.

**Comment by neilalexander** [comment]
Can you please see if this behaviour is any better as of commit [a572f4d](https://github.com/matrix-org/dendrite/commit/a572f4db034e13aa38e122d1c4233b15e2356494)?

**Comment by grisu48** [comment]
Hi, I'm seeing the same issue. I can send messages within the instance, but anything from outside doesn't come through.

I'm seeing a lot of the following errors in my log:

    time="2022-02-09T07:51:35.290943700Z" level=error msg="failed to query device keys for some users" context=missing failed=1 server_name=libre.brussels total=1 wait=1h0m0s
    time="2022-02-09T07:51:45.290814047Z" level=error msg="failed to query device keys for some users" context=missing failed=1 server_name=jloa.ovh total=1 wait=1h0m0s
    time="2022-02-09T07:51:45.348646367Z" level=error msg="failed to query device keys for some users" context=missing failed=1 server_name=thebrown.men total=1 wait=1h0m0s
    time="2022-02-09T07:51:45.382300790Z" level=error msg="failed to query device keys for some users" context=missing failed=2 server_name=chatserver.ca total=2 wait=1h0m0s
    time="2022-02-09T07:51:55.292139584Z" level=error msg="failed to query device keys for some users" context=missing failed=1 server_name=bergercloud.eu total=1 wait=1h0m0s

@neilalexander I tried to build the container from commit a2b4777ae5c4aa06ce7933bbd1b251bd777788b2 however the issue persists and the above stated error messages are still flowing.

**Comment by Undef-a** [comment]
with a2b4777 federation wasn't perfect, but was far better than 0.6.2 (where just about everything was locked up).

**Comment by grisu48** [comment]
I just updated to 0.6.3 and federation is still broken. When grepping for `level=error` in the docker container output, I still see a lot of "failed to query device keys for some users" entries, same as [above](https://github.com/matrix-org/dendrite/issues/2150#issuecomment-1033458744). The instance was working just fine prior to updating to 0.6.0, now internal messaging works but federation is still broken.

**Comment by stintel** [comment]
Broken for me as well in 0.6.3. Downgrading to 0.6.0 doesn't help. Downgrading further seems to require a database rollback, which is not an option as these backups have expired already.

**Comment by neilalexander** [comment]
Can you please try the latest `main` commit 5106cc807cf22a95420b24f6bfdd5c9ac8aa06de and report back on if it helps or not?

**Comment by grisu48** [comment]
I tried a new docker container with https://github.com/matrix-org/dendrite/commit/5106cc807cf22a95420b24f6bfdd5c9ac8aa06de and the issue is still present.

In addition now also the inter-instance communication is broken. Also: when logging in via my Android phone the app was performing a initial sync, despite me being logged in before.

When grepping for `level=error` I still see a lot of the "failed to query device keys for some user context=missing" errors.

I'm attaching here the output of `docker logs dendrite_monolith_1` in case you find this useful: [dendrite-logs.txt](https://github.com/matrix-org/dendrite/files/8053150/dendrite-logs.txt)

**Comment by Undef-a** [comment]
Using 5106cc8 helps a little. Now rooms all correctly sync up immediately after restarting dendrite. Over the next 10-30 minutes the problem rooms will start to drop events.

**Comment by stintel** [comment]
Unfortunately 5106cc807cf22a95420b24f6bfdd5c9ac8aa06de doesn't help at all here. I have not a single message after February 8 in any of the rooms I'm in. At that time I was running 0.6 since January 29. So for me the problem started with 0.6, but only ~10 days after upgrading to it.

**Comment by grisu48** [comment]
Short update: https://github.com/matrix-org/dendrite/commit/5106cc807cf22a95420b24f6bfdd5c9ac8aa06de seems to help. On Sunday after deploying my instance was still silent, however today I see that some of the noisier channels are finally filling again with messages from Sunday onwards. I still see a message hole between the date of updating to 0.6 and Sunday.
Also intra-instance communications works again.

I keep monitoring this issue, but I'm mildly optimistic that https://github.com/matrix-org/dendrite/commit/5106cc807cf22a95420b24f6bfdd5c9ac8aa06de might help to resolve the issue or at least help.

**Comment by alistair23** [comment]
I am having the same issue, lots of `failed to query device keys for some users` in the logs. Using https://github.com/matrix-org/dendrite/commit/5a39512f5f35b13adea3afc2e366e01ec73924de is no help

**Comment by neilalexander** [comment]
FWIW `failed to query device keys for some users` is specific to E2EE and ultimately a separate issue to failing to federate in public rooms.

Out of curiosity, are you all running the internal NATS deployment built into Dendrite or standalone NATS Server? If any of you are running a standalone NATS Server, which options are you running with?

**Comment by alistair23** [comment]
I deleted the jetstream dir (https://github.com/matrix-org/dendrite/issues/2181) and now it appears to be working after waiting awhile. I also bumped my max connections up to try and avoid https://github.com/matrix-org/dendrite/issues/2173

I'm using the NATS build into Dendrite

**Comment by grisu48** [comment]
I'm also using the NATS build directly into Dendrite. I am using the same config as provided in the project [yaml example](https://github.com/matrix-org/dendrite/blob/main/dendrite-config.yaml#L72):

```yaml
  # Configuration for NATS JetStream
  jetstream:
    # A list of NATS Server addresses to connect to. If none are specified, an
    # internal NATS server will be started automatically when running Dendrite
    # in monolith mode. It is required to specify the address of at least one
    # NATS Server node if running in polylith mode.
    #addresses:
    #  - jetstream:4222

    # Keep all NATS streams in memory, rather than persisting it to the storage
    # path below. This option is present primarily for integration testing and
    # should not be used on a real world Dendrite deployment.
    in_memory: false

    # Persistent directory to store JetStream streams in. This directory 
    # should be preserved across Dendrite restarts.
    storage_path: ./

    # The prefix to use for stream names for this homeserver - really only
    # useful if running more than one Dendrite on the same NATS deployment.
    topic_prefix: Dendrite

  # Configuration for Prometheus metric collection.
```
