### ISSUE TITLE
Cant run docker monolith with postgres

### ISSUE THREAD

**Issue by andzejsp** [matrix-org/dendrite#2932]
### Background information

- **Dendrite version or git SHA**: just now cloned from this github
- **Monolith or Polylith?**: Monolith
- **SQLite3 or Postgres?**: Postgres
- **Running in Docker?**: Docker
- **`go version`**: "go version go1.18.1 linux/amd64"

### Description

- **What** is the problem: "Cant connect to postgress."
- **Who** "is affected: Me, myself and I"
- **How** is this bug manifesting: "Failed to set up global database connections" error="failed to find maximum connections"
- **When** did this first appear: "Now"

### Steps to reproduce

I have written a guide for myself wich i have made few moths ago and it worked on my other system, but when i tried it today i get this error:

Please see bellow:
[https://github.com/andzejsp/HomeLab/blob/master/README.md#matrix-dendrite-docker-deployment-postgresql](https://github.com/andzejsp/HomeLab/blob/master/README.md#matrix-dendrite-docker-deployment-postgresql)

The only difference im testing on local network this, and i have no domains or fqdn, so under: dendrite-sample.monolith.yaml I left localhost.

```yaml
global:
  # The domain name of this homeserver.
  server_name: localhost
```

I also tried adding: command: postgres -c max_connections=1000 to the postgres service in the compose.yaml, didnt help.

```yaml
version: "3.4"
services:
  postgres:
    hostname: postgres
    image: postgres:14
    restart: always
    command: postgres -c max_connections=1000
    volumes:
```

Log snippet:

```
goroutine 1 [running]:
github.com/sirupsen/logrus.(*Entry).log(0xc0003f9b20, 0x0, {0xc0000cac60, 0x2c})
        github.com/sirupsen/logrus@v1.9.0/entry.go:260 +0x4a7
github.com/sirupsen/logrus.(*Entry).Log(0xc0003f9b20, 0x0, {0xc0000d0ec8?, 0xc0000d0f28?, 0x4617a9?})
        github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
        github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/MFAshby/stdemuxerhook.(*StdDemuxerHook).Fire(0x0?, 0xc0003f99d0)
        github.com/MFAshby/stdemuxerhook@v1.0.0/stdemuxerhook.go:58 +0x19e
github.com/sirupsen/logrus.LevelHooks.Fire(0xc0000d1008?, 0xd0fd8?, 0x1?)
        github.com/sirupsen/logrus@v1.9.0/hooks.go:28 +0x82
github.com/sirupsen/logrus.(*Entry).fireHooks(0xc0003f99d0)
        github.com/sirupsen/logrus@v1.9.0/entry.go:280 +0x1dc
github.com/sirupsen/logrus.(*Entry).log(0xc0003f9960, 0x0, {0xc0000cac30, 0x2c})
        github.com/sirupsen/logrus@v1.9.0/entry.go:242 +0x390
github.com/sirupsen/logrus.(*Entry).Log(0xc0003f9960, 0x0, {0xc0000d14b0?, 0x1651320?, 0xc00044a9a0?})
        github.com/sirupsen/logrus@v1.9.0/entry.go:304 +0x4f
github.com/sirupsen/logrus.(*Entry).Panic(...)
        github.com/sirupsen/logrus@v1.9.0/entry.go:342
github.com/matrix-org/dendrite/setup/base.NewBaseDendrite(0xc0001c2000, {0x1872153, 0x8}, {0xc0000d1d00, 0x0, 0x67000000025cba20?})
        github.com/matrix-org/dendrite/setup/base/base.go:223 +0xa2a
main.main()
        github.com/matrix-org/dendrite/cmd/dendrite-monolith-server/main.go:69 +0x35f
time="2023-01-07T15:07:20.742965729Z" level=info msg="Dendrite version 0.10.8+ed497aa"
time="2023-01-07T15:07:20.743230708Z" level=debug msg="Setting DB connection limits" conn_max_lifetime=-1s data_source_name="postgresql://monolith/dendrite?sslmode=disable" max_idle_conns=5 max_open_conns=90
time="2023-01-07T15:07:20.743806900Z" level=panic msg="Failed to set up global database connections" error="failed to find maximum connections: dial tcp 172.26.0.3:5432: connect: connection refused"
panic: (*logrus.Entry) 0xc000215ab0
```

All i wanted to  run the matrix on LAN. And i want it on docker so that i dont get my system messed up with junk all around.

<!--
Describe how what happens differs from what you expected.

If you can identify any relevant log snippets from server logs, please include
those (please be careful to remove any personal or private data). Please surround them with
``` (three backticks, on a line on their own), so that they are formatted legibly.

Alternatively, please send logs to @kegan:matrix.org or @neilalexander:matrix.org
with a link to the respective Github issue, thanks!
-->

**Comment by Azanul** [comment]
In you config yaml, what does your database connection string look like? Does it correspond with your postgres?

**Comment by S7evinK** [comment]
Sounds like there's no Postgres listening at 172.26.0.3?
As per your guide, you have `connection_string: postgresql://dendrite:itsasecret@monolith/dendrite?sslmode=disable`
So Dendrite is trying to connect to "monolith" as the Postgres server, which should probably be "postgres" (the other container)

**Comment by andzejsp** [comment]
But they are supposed to be on the same network? 
```yaml
networks:
      - internal
 ```
According to the compose file on this repo for monolith:

```yaml
version: "3.4"
services:
  postgres:
    hostname: postgres
    image: postgres:14
    restart: always
    volumes:
      - ./postgres/create_db.sh:/docker-entrypoint-initdb.d/20-create_db.sh
      # To persist your PostgreSQL databases outside of the Docker image, 
      # to prevent data loss, modify the following ./path_to path:
      - ./path_to/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: itsasecret
      POSTGRES_USER: dendrite
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dendrite"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  monolith:
    hostname: monolith
    image: matrixdotorg/dendrite-monolith:latest
    command: [
      "--tls-cert=server.crt",
      "--tls-key=server.key"
    ]
    ports:
      - 8008:8008
      - 8448:8448
    volumes:
      - ./config:/etc/dendrite
      - ./media:/var/dendrite/media
    depends_on:
      - postgres
    networks:
      - internal
    restart: unless-stopped

networks:
  internal:
    attachable: true
```

The docker ps showed that postgres was healthy and was running, i haven't tried to connect to it manually, but i could try that once im back at the location in few days. But honestly im not sure why the ip for postgress is 172.26.. from the monolith logs, because on docker ps the postgress was bound to 0.0.0.0:someport if i remember correctly.
