### ISSUE TITLE
Guest not  joining room with guest access

### ISSUE THREAD

**Issue by Gredin67** [matrix-org/dendrite#3163]
### Background information
- **0.13.1**:
- ** Postgres**:
- **debian yunohost** https://github.com/YunoHost-Apps/dendrite_ynh/:
- **go version `1.20`**:
- **Element Web**:

### Description
I can register as guest from Element, but cannot join room `#guest-room:homeserver.tld` that is public and has guest access activated. Here is an extract of my `dendrite.yaml`:
```
  registration_disabled:     False
  guests_disabled:   False
  registration_shared_secret:  xxxxxxxxxxxxx
  enable_registration_captcha: true
  # Settings for ReCAPTCHA.
  recaptcha_public_key: "xxxxxxxxx"
  recaptcha_private_key: "xxxxxxxxxx"
  #recaptcha_bypass_secret: ""
  #recaptcha_siteverify_api: ""

  # To use hcaptcha.com instead of ReCAPTCHA, set the following parameters, otherwise just keep them empty.
  recaptcha_siteverify_api: "https://hcaptcha.com/siteverify"
  recaptcha_api_js_url: "https://js.hcaptcha.com/1/api.js"
  recaptcha_form_field: "h-captcha-response"
  recaptcha_sitekey_class: "h-captcha"
  auto_join_rooms:
    - "#guest-room:homeserver.tld"
```

in synapse, to be able to access a room as guest, this room should be listed in `auto_join_room`  and followinf setting should be set `auto_join_rooms_for_guests: true`. 

Could this be related ?
