### ISSUE TITLE
helm: broken ingress

### ISSUE THREAD

**Issue by wrenix** [matrix-org/dendrite#3175]
current in helm-chart version: 0.13.1 (after #3077)

i got the host `https` with the following values:
```yaml
dendrite_config:
  global:
    server_name: "example.net"
    # without https needed for https://federationtester.matrix.org
    well_known_server_name: "dendrite.example.net:443"
    # https needed for fluffychat
    well_known_client_name: "https://dendrite.example.net:443"
``` 

@Omar007 and @S7evinK do you take a look?
