### ISSUE TITLE
SQLite is not working

### ISSUE THREAD

**Issue by paigeadelethompson** [matrix-org/dendrite#3435]
followed the documentation @ https://matrix-org.github.io/dendrite/installation/manual/database and it don't work

```
monolith-1  | time="2024-09-28T13:21:13.627063518Z" level=panic msg="failed to connect to room server db" error="near \"SEQUENCE\": syntax error"
monolith-1  | panic: (*logrus.Entry) 0xc0002682a0
```

```
  database:
    connection_string: file:dendrite_component.db
    max_open_conns: 5
    max_idle_conns: 5
    conn_max_lifetime: -1
```

tried `file:///` and it dont work
